### ISSUE TITLE
There are a few bare <i>s that need semantics

### ISSUE THREAD

**Issue by robinwhittleton** [b-t-k/mack-reynolds_short-fiction#2]

**Comment by b-t-k** [comment]
A bunch of these are made-up alien languages which I think we just leave bare. I fixed the others.

**Comment by robinwhittleton** [comment]
Ah, OK. For consistency I’ve sometimes tagged those with `xml:lang="art"` (artificial languages) or `xml:lang="zzx"` (“No linguistic content; Not applicable”) but I think that’s just me being nerdy ;)
