### ISSUE TITLE
Imprint and colophon should list all the sources including archive.org

### ISSUE THREAD

**Issue by robinwhittleton** [b-t-k/mack-reynolds_short-fiction#3]
See https://github.com/standardebooks/kate-chopin_short-fiction/blob/master/src/epub/text/colophon.xhtml for an example of multiple sources.

**Comment by b-t-k** [comment]
I should list all 21 sources or just add the 3 that aren't pgpd?

**Comment by robinwhittleton** [comment]
I think I’d go for just the three, but @acabal might have more of an opinion?

**Comment by b-t-k** [comment]
I added the three extras. will change if necessary

**Comment by acabal** [comment]
That's fine, though you broke a tag with a newline on line 24 of colophon.xhtml. That's probably not valid html.

**Comment by b-t-k** [comment]
Fixed
